Feautre/champion main UI viewcontroller and collection view
f-lab-edu/LOL_Info_App pull request #14
Opened 2024-02-28 06:21 UTC by DeokHo98

## Issue Number
close #10 

## 작업내용
챔피언 메인 화면을 담당할 ViewController와 해당 화면에서 챔피언들의 리스트를 보여줄 collectionView를 구현 했습니다.

## 상세 작업내용
### ChampionMainViewController 구현
- 리스팅을 필터할 text의 입력부분은 리스트를 밑으로 스크롤해도 사용할수 있게 UISearchController로 구현 했습니다.
- 리스트는 UICollectionView로 구현했습니다.
- 리스트를 받아올때 로딩중인걸 표시해주는 용도로 UIActivityIndicatorView를 구현했습니다.
    
### ChampionMainCollectionView 구현
- 즐겨찾기 리스트는 가로, 챔피언 리스트는 세로이기 때문에 CollectionView의 Composional Layout을 활용 해서 구현 했습니다.
- CollectionView의 레이아웃 부분은 LayoutProvider를 구현해서 따로 분리했습니다.
    
### UIColor Extension 구현
- 다크모드도 대응하기 위해 Custom ColorSet을 추가했고 이걸 가져오는 코드를 UIColor Extension으로 구현 했습니다.

2024-03-05 12:36 UTC, abdul0986 requested changes
피드백 반영 부탁드립니다.

2024-03-05 12:36 UTC, abdul0986 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/PresentationLayer/CollectionView/ChampionMainCollectionViewLayoutProvider.swift
> +    }
서브 enum으로 나누어 구성해보는 것이 어떨까요?

2024-03-05 12:36 UTC, abdul0986 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/PresentationLayer/CollectionView/ChampionMainCollectionViewLayoutProvider.swift
> +    }
작은 단위로 분리해봐주시면 좋을 것 같습니다.

2024-03-08 05:34 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/PresentationLayer/CollectionView/ChampionMainCollectionViewLayoutProvider.swift
> +    }
반영했습니다!

2024-03-08 05:39 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/PresentationLayer/CollectionView/ChampionMainCollectionViewLayoutProvider.swift
> +    }
프로토콜을 이용해서 한번 분리해봤습니다.

Commons에 ComposiotionalLayoutProvider라는 프로토콜을 생성했습니다.

```swift
protocol CompositionalLayoutProvider {

    ///Layout Group을 만들때 필요한 Item을 생성하는 함수입니다.
    func getLayoutItem() -> NSCollectionLayoutItem

    ///Layout Section을 만들때 필요한 Gruop을 생성하는 함수입니다.
    func getLayoutGroup() -> NSCollectionLayoutGroup

    ///Compositional Layout을 만들때 필요한 Section을 생성하는 함수입니다.
    func getLayoutSection() -> NSCollectionLayoutSection

}
```

그리고 이것을 채택한 두가지의 Provider 
ChampionMainFavoriteListLayoutProvider, ChampionMainListLayoutProvider를 만들어서 분리했습니다!

```swift
extension ChampionMainListLayoutProvider: CompositionalLayoutProvider {
    func getLayoutItem() -> NSCollectionLayoutItem {
        let itemSize = NSCollectionLayoutSize(
            widthDimension: .fractionalWidth(Metric.Item.size),
            heightDimension: .fractionalHeight(Metric.Item.size)
        )
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        item.contentInsets = NSDirectionalEdgeInsets(
            top: Metric.Item.topAndBottom,
            leading: Metric.Item.side,
            bottom: Metric.Item.topAndBottom,
            trailing: Metric.Item.side
        )
        return item
    }

    func getLayoutGroup() -> NSCollectionLayoutGroup {
        let item = getLayoutItem()
        let groupSize = NSCollectionLayoutSize(
            widthDimension: .fractionalWidth(Metric.Group.width),
            heightDimension: .estimated(Metric.Group.height)
        )
        let group = NSCollectionLayoutGroup.vertical(
            layoutSize: groupSize,
            subitems: [item]
        )
        return group
    }

    func getLayoutSection() -> NSCollectionLayoutSection {
        let group = getLayoutGroup()
        let section = NSCollectionLayoutSection(group: group)
        section.contentInsets = NSDirectionalEdgeInsets(
            top: Metric.Section.top,
            leading: Metric.Section.side,
            bottom: Metric.Section.bottom,
            trailing: Metric.Section.side
        )
        let sectionHeaderSize = NSCollectionLayoutSize(
            widthDimension: .fractionalWidth(Metric.Header.width),
            heightDimension: .estimated(Metric.Header.height)
        )
        section.boundarySupplementaryItems = [
            NSCollectionLayoutBoundarySupplementaryItem(
                layoutSize: sectionHeaderSize,
                elementKind: UICollectionView.elementKindSectionHeader,
                alignment: .top
            )
        ]
        return section
    }
}
```

2024-03-25 04:44 UTC, abdul0986 requested changes
피드백 확인 부탁드려요

2024-03-25 04:44 UTC, abdul0986 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/PresentationLayer/CollectionView/ChampionMainCollectionView.swift
> +            }
`sectionType`에 따라서 `ChampionMainListLayoutProvider()`와 `ChampionMainFavoriteListLayoutProvider()` 의 구현체를 선택하고 있는데, 이 부분은 별도로 `sectionType` 을 인자값으로 받아 `CompositionalLayoutProvider`을 리턴하는 **_팩토리 메소드 패턴_**으로 처리하면 좋을 것 같습니다. 

**팩토리 메소드 패턴**은 객체 생성을 팩토리(Factory) 클래스로 캡슐화 처리하여 대신 생성하게 하는 생성 디자인 패턴입니다.

2024-03-25 04:44 UTC, abdul0986 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/PresentationLayer/CollectionView/LayoutProvider/ChampionMainFavoriteListLayoutProvider.swift
> +    }
메소드가 다소 깁니다. 서브 메소드로 분리해주세요.

2024-03-29 06:40 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/PresentationLayer/CollectionView/LayoutProvider/ChampionMainFavoriteListLayoutProvider.swift
> +    }
sectionHeader를 생성하는 코드를 분리하는게 맞다고 생각되어 분리했습니다!

2024-03-29 07:52 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/PresentationLayer/CollectionView/ChampionMainCollectionView.swift
> +            }
CompositionalLayoutProvider 인스턴스의 생성을 담당하는 팩토리 객체를 구현했습니다.

2024-03-31 13:01 UTC, abdul0986 approved these changes
LGTM

2024-04-01 08:43 UTC, merged