Feature/networking and championmain repository
f-lab-edu/LOL_Info_App pull request #9
Opened 2024-02-25 17:06 UTC by DeokHo98

# 이슈
기존 PR에서 Squash 중에 실수로 인해 main 브렌치와 연결 자체가 끊겨버리는 문제 때문에 새로운 PR을 요청하게 되었습니다.
다음부턴 Squash를 할때 보다 신중하게 하겠습니다.

## Issue Number
close #3 

## 작업내용
- 챔피언 메인 DataLayer 구현
- 로깅을 위한 OSLog Extension 구현
- URL.plist 파일에 접근하기 위한 Bundle Extension 구현

## DataLayer 다이어 그램
![스크린샷 2024-02-25 오후 11 04 56](https://github.com/f-lab-edu/LOL_Info_App/assets/93653997/58f30d5b-aea6-4f18-a0b3-fee781582425)
     
    
## 상세 작업 내용
   
### Requestable 구현
- 프로젝트의 어떠한 EndPoint에서 사용할수 있는 객체입니다. 그렇기 때문에 Common에 구현했습니다.
- 프로토콜을 채택한 EndPoint 객체가 서버와 통신에 필요한 변수 (URL, HTTPMethod, Param, Header) 등등의 변수를 구현하도록 정의 했습니다.   
- 프로토콜을 Extension 했을때의 활용방법중 하나인 메서드의 기본구현 기능을 이용해 프로토콜을 채택한 EndPoint 객체가 메서드 구현 없이    
 requestData(서버통신 메서드) 를 사용할수 있도록 구현했습니다.
- 서버에서 받아온 JSON을 Data로 변환 그리고 또 DTO로 변환하여 반환 합니다.
    
### 챔피언 Endpoint 구현
- 챔피언에 관련된 어떤 Repository에서도 사용할 수 있는 객체입니다.
- 챔피언에 관련된 API 통신에 사용할 변수를 정의한 EndPoint 객체를 구현했습니다.
- 챔피언에 관련된 API를 case별로(main, detail 등등) 사용하기 위해 Enum으로 구현했습니다.
    
### 챔피언 Main Repository 구현
- 챔피언 Main Usecase 에서 사용될 객체입니다. (메인화면에 관련된 데이터를 반환)
- DTO 형태로 받아온 데이터를 Entity 형태로 변환하여 반환 합니다.
- 의존성 역전 원칙과 Testable한 코드를 위해 프로토콜을 이용해 구현했습니다.
    
### OSLog Extension 구현
- network, debug, error 3가지로 로그를 분류했습니다.
- 로그에 표시되는 내용은 파라미터로 받는 message, arguments, 파일이름, 함수이름, 해당코드의 라인숫자 이렇게 5가지 입니다.
- 파라미터로 받는 파일이름, 함수이름, 해당코드의 라인숫자는 기본값을 제공해 사용하는곳에선 message와 arguments만 입력받게 구현했습니다.
     
![스크린샷 2024-02-26 오전 12 12 06](https://github.com/f-lab-edu/LOL_Info_App/assets/93653997/69ada4df-ca4b-4115-b67f-22f14fb3d946)

#### Xcode 콘솔 로그
![스크린샷 2024-02-26 오전 12 11 59](https://github.com/f-lab-edu/LOL_Info_App/assets/93653997/7f58e0a6-6c71-4b38-ad26-4c5c7eb02c5a)
      

#### mac 콘솔 로그
![스크린샷 2024-02-26 오전 12 12 23](https://github.com/f-lab-edu/LOL_Info_App/assets/93653997/42e2ada8-e5bb-467b-961f-33a660330227) 
      
     
### URL.plist 파일에 접근하기 위한 Bundle Extension 구현
- Enum을 이용해 Key를 case별로 정의 하여 URL.plist 파일에 접근하여 URL을 가져올수 있게 구현했습니다.

2024-02-27 06:05 UTC, DeokHo98 commented
다음주 멘토링에서 ChampionEndpoint 객체의 리팩토링을 요청해달라고 하신 내용이 있었습니다

2024-02-27 14:06 UTC, sqlpro commented
데이터 계층에 대한 다이어그램은 일단 구체화해 놓은 것에서 합격입니다. 
다음 멘토링 시간에는 그려놓으신 데이터 계층 다이어그램에 대한 설명을 준비해주세요~!!

2024-02-27 14:19 UTC, sqlpro requested changes
코드가 깔끔합니다. 조금만 더 보완하면 매우 좋을 듯 합니다.

2024-02-27 14:19 UTC, sqlpro commented on LOLInfoApp/LOLInfoApp/Commons/Constants.swift
> +struct Constants {
`separator` / `lineBreak` 등에 대한 Constant라면 뭔가 Verbose한 `Constants`라는 네이밍 대신에 구체적인 이름을 부여해 줄 수 있을 것 같은데 고민해봐주세요

2024-02-27 14:19 UTC, sqlpro commented on LOLInfoApp/LOLInfoApp/Commons/Constants.swift
> +struct Constants {
struct로 상수값을 정의하는 것과 enum 타입으로 상수값을 정의하는 것 사이에서 어느 것이 더 나은지 생각해보면 좋겠습니다.

2024-02-27 14:19 UTC, sqlpro commented on LOLInfoApp/LOLInfoApp/Commons/Extension/Bundle.swift
코드가 깔끔합니다. 다만 "plist", "URL", "ChampionPath" 라는 문자열 리터럴이 사용되고 있는 것이 조금 아쉬운데요, 
Bundle 관련 상수나 enum으로 빼는 것은 어떠신가요

2024-02-27 14:19 UTC, sqlpro commented on LOLInfoApp/LOLInfoApp/Commons/Network/Requestable.swift
> +    }}
위 두 함수는 굳이 함수명을 `loggingRequest()`/ `loggingResponse()` 로 구분하지 않고 아래와 같이 
- `logging()` 
- `logging(_ AFDataResponse)` 
하는 식으로 오버로딩 처리해서 작성이 가능할 것 같은데요. 어떠신가요?

2024-02-27 14:19 UTC, sqlpro commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/DataLayer/ChampionMainListDTO.swift
> +    let data: [String: ChampionMainListDTO.ChampionMainDTO]
`[String: ChampionMainListDTO.ChampionMainDTO]`는 타입이 너무 길어서 가독성이 좀 떨어지는데요, alias를 걸어주는 건 어떠신가요?

2024-02-27 23:34 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Commons/Constants.swift
> +struct Constants {
해당 Constant는 모두 String내 에서 사용하고 있기때문에 
이름을 StringConstants라고 수정하였습니다!

2024-02-27 23:41 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Commons/Constants.swift
> +struct Constants {
상수값만을 목적으로 하기때문에 enum으로 변경하여 불필요한 인스턴스 생성을 아예 막는것이 나아보입니다.

2024-02-28 02:19 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Commons/Constants.swift
> +struct Constants {
해당 Constant는 모두 String에서 사용하는 상수이기때문에
Commons 안에 Constants라는 폴더를 새로 만들어 그안에 넣었고
StringConstants 라고 이름을 변경했습니다.

2024-02-28 02:20 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Commons/Constants.swift
> +struct Constants {
구조체로 했을경우 의도치 않은 인스턴스를 생성할수 있는 가능성이 생기는것 같습니다. 상수값만을 목적으로 하기때문에 enum으로 변경하여 인스턴스 생성의 가능성을 아예 막는방향으로 수정했습니다!

2024-02-28 02:20 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Commons/Extension/Bundle.swift
Common에 Constatns 폴더안에 Bundle+Constants (파일 네이밍은 Bundle과 관련된 Constants이기때문에 +를 붙혔습니다) 라는 파일을 만들었고 그안에 Enum으로 생성하여 정리했습니다.

"plist"는 Bundle 호출 함수에서 파일의 타입 파라미터에 들어가기때문에 BundleFileType이라는 Enum을 생성하여 안에 정리했고 

"URL", "ChampionPath"는 Bundle 호출 함수에서 리소스 파라미터에 들어가기때문에 BundleResource Enum을 생성하여 안에 정리했습니다.

2024-02-28 02:21 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Commons/Network/Requestable.swift
> +    }}
오버로딩으로 처리했을때 간결해진다는 장점이 있긴 하지만 
만약 처음 이 함수를 사용하는 다른 개발자가 해당 함수를 호출할때 함수의 호출부만 보고 어떤 일을 하는 함수일지 알수 있을까가 의문이 라는 생각이 듭니다.

* logging(_ AFDataResponse) 같은경우는 파라미터를 보고 유추가 가능하지만
* logging() 같은경우는 구현부를 보지 않고는 유추할수가 없다고 생각합니다.

물론 현재는 2개의 함수의 구현부가 그리 복잡하지 않아서 금방 어떤 함수인지 알아볼수있긴 한데.. 
오버로딩으로 처리하는게 나을까요...?

2024-02-28 02:21 UTC, DeokHo98 commented on LOLInfoApp/LOLInfoApp/Scenes/Champion/Main/DataLayer/ChampionMainListDTO.swift
> +    let data: [String: ChampionMainListDTO.ChampionMainDTO]
가독성 향상을 위해 typealias를 사용하면 좋을것 같습니다! 반영하겠습니다!

2024-03-05 12:00 UTC, abdul0986 approved these changes
LGTM

2024-03-07 07:37 UTC, merged